spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/habitpet
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
